// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//import 'firebase_options.dart';

/// // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALH06WK3eeY8O-kNRALoXWklZFbDciZ4s',
    appId: '1:257601890789:web:6a73de11847d0413c8670c',
    messagingSenderId: '257601890789',
    projectId: 'database-ad668',
    authDomain: 'database-ad668.firebaseapp.com',
    storageBucket: 'database-ad668.appspot.com',
    measurementId: 'G-2JVFNZB9CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYCXfPpyjykDq1POiLmNmUGShc0tQ7Erk',
    appId: '1:257601890789:android:4861c8d922d5a5e7c8670c',
    messagingSenderId: '257601890789',
    projectId: 'database-ad668',
    storageBucket: 'database-ad668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiMtq3GUGM7Zb8xKhBZxDCekO5sJKaEtc',
    appId: '1:257601890789:ios:6874bf0a56c57868c8670c',
    messagingSenderId: '257601890789',
    projectId: 'database-ad668',
    storageBucket: 'database-ad668.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiMtq3GUGM7Zb8xKhBZxDCekO5sJKaEtc',
    appId: '1:257601890789:ios:6874bf0a56c57868c8670c',
    messagingSenderId: '257601890789',
    projectId: 'database-ad668',
    storageBucket: 'database-ad668.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALH06WK3eeY8O-kNRALoXWklZFbDciZ4s',
    appId: '1:257601890789:web:d8e6c5605f95aa65c8670c',
    messagingSenderId: '257601890789',
    projectId: 'database-ad668',
    authDomain: 'database-ad668.firebaseapp.com',
    storageBucket: 'database-ad668.appspot.com',
    measurementId: 'G-0CF3NEL7TD',
  );
}
